# Documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: '/action'
    schedule:
      interval: 'monthly'
      time: '11:00'
      timezone: 'Europe/Zurich'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      jest:
        applies-to: version-updates
        patterns:
          - '*jest'
    ignore:
      # Since `v21.0.0`, package `@octokit/rest` is ESM
      - dependency-name: '@octokit/rest'
        update-types: [version-update:semver-major]
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '11:00'
      timezone: 'Europe/Zurich'
