name: CI

on: push

jobs:
  generateTOC:
    runs-on: ubuntu-latest
    name: Generate Table of Contents
    steps:
      - name: TOC Generator
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ci:
    name: Run Build and check output is checked-in
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install NPM Packages
        run: |
          cd action
          npm install
      - name: Build
        run: |
          cd action
          npm run build
      - name: Check no files have changes
        run: git diff --exit-code
  checks:
    name: Check file formatting, linting and Typescript types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install NPM Packages
        run: |
          cd action
          npm install
      - name: Check Typescript types
        run: |
          cd action
          npm run check-types
      - name: Check formatting
        if: success() || failure()
        run: |
          cd action
          npm run check-formatting
      - name: Linting
        if: success() || failure()
        run: |
          cd action
          npm run lint
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install NPM Packages
        run: |
          cd action
          npm install
      - name: Run Unit Tests
        run: |
          cd action
          npm run test -- --coverage
      - name: Submit to CodeCov
        uses: codecov/codecov-action@v2
        with:
          files: ./action/.coverage/lcov.info
          fail_ci_if_error: true
